# Generated by Django 3.0.2 on 2020-01-28 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Default'), (1, 'Active'), (2, 'Archived')], default=1)),
                ('description', models.CharField(max_length=150, null=True)),
                ('labels', models.ManyToManyField(to='TrackerApp.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Archived')], default=1)),
                ('description', models.CharField(max_length=150, null=True)),
                ('scheduled_for', models.DateTimeField(null=True)),
                ('labels', models.ManyToManyField(to='TrackerApp.Label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackerApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('notes', models.CharField(max_length=150, null=True)),
                ('labels', models.ManyToManyField(to='TrackerApp.Label')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TrackerApp.Task')),
            ],
        ),
    ]
